# Modified Nextrain workflow from 2020-09-11
# MIT License
# Copyright (c) 2020 Nextstrain, full text https://github.com/nextstrain/ncov/blob/master/LICENSE


# This file contains defaults for the "config" object used in the Snakefile.
# To temporarily override or provide a value, you can use snakemake's --config
# or --configfile options.
---

# conda environment file to use by default
conda_environment: "/envs/nextstrain.yaml"

# These are the two main starting files for the run
# Files are previously downloaded from GISAID database, Downloads > nextmeta and nextfasta to the data folder
sequences: "data/200911_sequences.fasta"
metadata: "data/200911_metadata.tsv"


# Define files used for external configuration. Common examples consist of a
# list of strains to include and exclude from analyses, a reference sequence to
# align sequences to.
files:
  include: "files/include.txt"
  exclude: "files/exclude.txt"
  reference: "files/reference_seq.gb"

# Filter settings
filter:
  # Require nearly full-length genomes.
  min_length: 27000

  # Omit sequences with incomplete date annotations, and USA seqs without a state.
  exclude_where: "division='USA' date='2020' date='2020-01-XX' date='2020-02-XX' date='2020-03-XX' date='2020-04-XX' date='2020-05-XX' date='2020-06-XX' date='2020-01' date='2020-02' date='2020-03' date='2020-04' date='2020-05' date='2020-06'"


# Alignment settings
# Alignments are partitioned into smaller groups to speed up the overall alignment process.
# The number of sequences per group determines the run time of a single alignment job.
partition_sequences:
  sequences_per_group: 150

# Mask settings determine how the multiple sequence alignment is masked prior to phylogenetic inference.
mask:
  # Number of bases to mask from the beginning and end of the alignment. These regions of the genome
  # are difficult to sequence accurately.
  mask_from_beginning: 100
  mask_from_end: 50

  # Specific sites to mask in the reference genome's coordinates.
  # These are 1-indexed coordinates of sites that have been identified as prone to sequencing errors.
  # 13402, 24389 and 24390 are restricted to Belgian samples
  mask_sites: "13402 24389 24390"


# This is where we define which builds we'd like to run.
# Each build needs a name, a defined subsampling process, and geographic attributes used for subsampling.
# Geography is specified by build attributes (e.g., `region`, `country`, `division`, `location`) that are referenced from subsampling schemes.
builds:
  # This build focuses on Europe samples
  # europe:
  #   subsampling_scheme: region_grouped_by_country
  #   region: europe
  eeurope:
    subsampling_scheme: earlyeurope

# # Define subsampling scheme
# Custom subsampling logic for regions like Europe where grouping by country
# is the smallest resolution required.
subsampling:
  region_grouped_by_country:
    # Focal samples for region
    region:
      group_by: "country year month"
      seq_per_group: 5
      exclude: "--exclude-where 'region!={region}'"
  earlyeurope:
    # Focal samples
    hubei:
      group_by: "year month"
      seq_per_group: 10
      query: --query "(division == 'Hubei') & (date<='2020-01-23')"
    italy:
      group_by: "year month"
      seq_per_group: 30
      query: --query "(country == 'Italy') & (date<='2020-01-08')"
    germany:
      group_by: "year month"
      seq_per_group: 30
      query: --query "(country == 'Germany') & (date<='2020-01-08')"
    france:
      group_by: "year month"
      seq_per_group: 20
      query: --query "(country == 'France') & (date<='2020-01-08')"
    spain:
      group_by: "year month"
      seq_per_group: 30
      query: --query "(country == 'Spain') & (date<='2020-01-08')"
    othereuropean:
      group_by: "year month"
      seq_per_group: 20
      query: --query "(region == 'Europe') & (country not in ['Italy', 'France', 'Germany', 'Spain']) & (date<='2020-01-08')"

tree:
  tree-builder-args: "'-ninit 10 -n 4'"

# TreeTime settings
refine:
  root: "Wuhan/Hu-1/2019 Wuhan/WH01/2019" #EPI_ISL_402125  EPI_ISL_406798
  clock_rate: 0.0008
  clock_std_dev: 0.0004
  coalescent: "skyline"
  date_inference: "marginal"
  divergence_unit: "mutations"
  clock_filter_iqd: 4


# BEAST2 analysis settings
beast:
  # XML file for analysis
  xml:  "200914_europe1.xml"
  # BEAST2 jar file path
  jar: "/cluster/home/ceciliav/BDMM-Prime.jar"
  # List of arallel mcmc chains to run 
  n_mcmc: [1,2]
  # Time for mcmc chains in cluster
  t_mcmc: 120:00
  # Burnin percentage when combining log files
  burnin: 10


