---
title: "Trace Results"
subtitle: "analysis 3,6 and 10"
author: "Cecilia Valenzuela"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output:
  beamer_presentation:
  theme: "Pittsburgh"
colortheme: "dove"
fonttheme: "structurebold"
highlight: pygments
classoption: "aspectratio=169"
fontsize: 8pt
tables: yes
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
options(knitr.kable.NA = '')
```

```{r libraries}
# Load libraries ---------------------------------------------------------------
library(argparse)
library(yaml)
library(tidyverse)
library(lubridate)
library(scales)
library(ggpubr)
library(ggsci)
library(ggridges)
library(patchwork)
library(hrbrthemes)
library(circlize)
library(chorddiag) 
library(ggforce)
library(ComplexHeatmap)
library(maps)
library(sf)
library(wpp2019)
library(gridExtra)
library(grid)
# Source files -----------------------------------------------------------------
source("./scripts/trajProcessing.R")
source("./scripts/utils.R")
```



```{r data}
# Analyze trace with priors
eu3 <- read.table("/Users/maceci/Documents/CBB Master/HS20/Master Thesis/sars-cov-2-eu-phylodynamics/results/europeC/201030_europe3_comb.log", header = TRUE) %>%
  pivot_longer(-Sample, names_to = "param", values_to = "value") %>% 
  mutate(analysis = "eu3") #%>%
# rename(R0SVChina = R0SVHubei.China)
eu6 <- read.table("/Users/maceci/Documents/CBB Master/HS20/Master Thesis/sars-cov-2-eu-phylodynamics/results/europeC/201211_europe6p2_comb.log", header = TRUE) %>%
  pivot_longer(-Sample, names_to = "param", values_to = "value") %>% 
  mutate(analysis = "eu6")
eu10 <- read.table("/Users/maceci/chains/210120_europe10a_comb.log", header = TRUE) %>%
  pivot_longer(-Sample, names_to = "param", values_to = "value") %>% 
  mutate(analysis = "eu10")
         # R0SVFrance = R0SVi1_France,
         # R0SVItaly = R0SVi1_Italy,
         # R0SVGermany = R0SVi1_Germany,
         # R0SVSpain = R0SVi1_Spain,
         # R0SVOtherEuropean = R0SVi1_OtherEuropean) 

trace <- bind_rows(bind_rows(eu3, eu6), eu10) %>%
  mutate(param = gsub("Hubei.", "", param)) %>%
  separate(param, into = c("param", "deme"), "SV") %>%
  separate(param, into = c("param", "mig"), "SM") %>%
  separate(deme, into = c("epoch1", "deme"), "_", fill = "left") %>%
  separate(mig, into = c("src", "dest"), "_to_") %>%
  separate(src, into = c("epoch2", "src"), "_", fill = "left") %>%
  unite(epoch, c("epoch1", "epoch2"), na.rm = TRUE)
```

## Origin

```{r origin}

prior <- dlnorm(seq(0,1,0.01), meanlog = -1.0, sdlog = 0.2)
b <- date(date_decimal(decimal_date(ymd("2020-03-08")) - seq(0,1,0.05)))
ggplot() +
  geom_density(data = trace %>% filter(param == "originBDMMPrime"),
               aes(value, color = analysis, fill = analysis), alpha = 0.3) +
  geom_line(aes(seq(0,1,0.01),prior)) +
  scale_x_continuous(labels = b, breaks = seq(0,1, 0.05)) +
  theme(axis.text = element_text(angle=270)) +
  scale_color_viridis_d(labels = c("eu3 - initial setup", "eu6 - GLM 2p no ind", "eu10 - GLM 2p ind\n R0 China fixed")) +
  scale_fill_viridis_d(labels = c("eu3 - initial setup", "eu6 - GLM 2p no ind", "eu10 - GLM 2p ind\n R0 China fixed"))
```

## R0

```{r r0}
prior <- dlnorm(seq(0,6,0.01), meanlog = 0.8, sdlog = 0.5)
ggplot() +
  geom_density(data = trace %>% filter(param == "R0", deme != "endtime"),
               aes(value, color = analysis, fill = analysis), alpha = 0.3) +
  facet_wrap(~deme) +
  #geom_line(aes(seq(0,1,0.01),prior)) +
  scale_color_viridis_d(labels = c("eu3 - initial setup", "eu6 - GLM 2p no ind", "eu10 - GLM 2p ind\n R0 China fixed")) +
  scale_fill_viridis_d(labels = c("eu3 - initial setup", "eu6 - GLM 2p no ind", "eu10 - GLM 2p ind\n R0 China fixed"))
```

## Migration rate
```{r migrate}

ggplot() +
  geom_density(data = trace %>% filter(param == "migrationRate", !is.na(dest)) %>% 
                 select(value, src, dest, analysis, epoch) %>% group_by(analysis),
               aes(value, color = interaction(epoch, analysis), fill = interaction(epoch, analysis)), alpha = 0.3) +
  facet_grid(src~dest, scales = "free") +
  scale_x_continuous(limits = c(0,4)) +
  scale_y_continuous(limits = c(0,20)) +
  scale_color_viridis_d() +
  scale_fill_viridis_d()
```

## Sampling proportion
```{r sp}

ggplot() +
  geom_density(data = trace %>% filter(param == "samplingProportion", deme != "endtime", epoch != "i0"),
               aes(value, color = interaction(epoch, analysis), fill = interaction(epoch, analysis)), alpha = 0.3) +
  facet_wrap(~deme, scales = "free") +
  scale_x_continuous(limits = c(0,0.1)) +
  #scale_y_continuous(limits = c(0,20)) +
  scale_color_viridis_d() +
  scale_fill_viridis_d()
```

## GLM 1 - FLight data
```{r glm1}

prior <- dnorm(seq(-10,10,0.01), mean = 0, sd = 4)
ggplot() +
  geom_density(data = trace %>% filter(param %in% c("scaleParamGLM.0", "scalerParamGLM.0")),
               aes(value, color = analysis, fill = analysis), alpha = 0.3) +
  geom_line(aes(seq(-10, 10,0.01), prior)) +
  #scale_x_continuous(labels = b, breaks = seq(0,1, 0.05)) +
  #theme(axis.text = element_text(angle=270)) +
  scale_color_viridis_d(labels = c("eu3 - initial setup", "eu6 - GLM 2p no ind", "eu10 - GLM 2p ind\n R0 China fixed")) +
  scale_fill_viridis_d(labels = c("eu3 - initial setup", "eu6 - GLM 2p no ind", "eu10 - GLM 2p ind\n R0 China fixed"))
```

## GLM 2 - distance
```{r glm2}

prior <- dnorm(seq(-10,10,0.01), mean = 0, sd = 4)
ggplot() +
  geom_density(data = trace %>% filter(param %in% c("scaleParamGLM.1", "scalerParamGLM.1")),
               aes(value, color = analysis, fill = analysis), alpha = 0.3) +
  geom_line(aes(seq(-10, 10,0.01), prior)) +
  #scale_x_continuous(labels = b, breaks = seq(0,1, 0.05)) +
  #theme(axis.text = element_text(angle=270)) +
  scale_color_viridis_d(labels = c("eu3 - initial setup", "eu6 - GLM 2p no ind", "eu10 - GLM 2p ind\n R0 China fixed")) +
  scale_fill_viridis_d(labels = c("eu3 - initial setup", "eu6 - GLM 2p no ind", "eu10 - GLM 2p ind\n R0 China fixed"))
```

